[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.8.2",
    "openai>=1.88.0",
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "streamlit>=1.46.0",
]
